version: '3.3'
services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - ./config:/config
    environment:
      - TZ=
      - PGID=
      - PUID=
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    labels:
      - homepage.name=Speedtest Tracker
      - homepage.group=Monitoring
      - homepage.icon=speedtest-tracker.png
      - homepage.description=Monitor your internet speed
      - homepage.href=URL
      - homepage.widget.type=speedtest
      - homepage.widget.url=URL

networks:
  default:
    external: true
    name: nginxproxymanager
