version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ./icons:/app/public/icons
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginxproxymanager
